server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin-db?createDatabaseIfNotExist=true
    username: user
    password: user
  application:
    name: spring-admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect



